### ISSUE TITLE
Configurable test dir path

### ISSUE THREAD

**Issue by ttimot24** [laravel/dusk#556] opened 2018-09-22 13:18 UTC
Hi!

Please make the hardcoded test dir path configurable, in Dusk command:

https://github.com/laravel/dusk/blob/master/src/Console/DuskCommand.php#L110

Maybe a test_path() helper would be useful in a lot of occasion.

Thanks!

**Comment by driesvints** [comment] 2018-11-01 12:53
Duplicate of #393

**Closed by driesvints** 2018-11-01 12:53 UTC
