### ISSUE TITLE
visiting a page object then testing it has redirected to another, using on(new Page) fails

### ISSUE THREAD

**Issue by thehiggster** [laravel/dusk#561] opened 2018-10-03 10:35 UTC
Simple test, to check that accessing the dashboard without authenticating, redirects you to the login page. "Actual path [/] does not equal expected path [/login]"

```
$browser->visit(new Dashboard())                          
    ->assertSee('Login')
    ->on(new Login());
});
```

^^ this fails at the on(new Login()) line but if I change the visit line, to the path instead of the Page object it works, as below. The screenshot, shows the login page correctly and the assertSee is updated.

```
$browser->visit('/')
    ->assertSee('Login')
    ->on(new Login());
```

Is there another way around this, or is it simply a bug?

* Tried to use pause(1000) (and bigger numbers) before the on call.
* Tried on('/login') < also fails.

Thanks, 
James

**Comment by staudenmeir** [comment] 2018-10-03 14:32
Please post the `Dashboard` class.

**Comment by thehiggster** [comment] 2018-10-10 11:14
```
class Dashboard extends Page
{
    /**
     * Get the URL for the page.
     *
     * @return string
     */
    public function url()
    {
        return '/';
    }

    /**
     * Assert that the browser is on the page.
     *
     * @param  Browser  $browser
     * @return void
     */
    public function assert(Browser $browser)
    {
        $browser->assertPathIs($this->url());
    }

    /**
     * Get the element shortcuts for the page.
     *
     * @return array
     */
    public function elements()
    {
        return [
            '@link-view-best-sellers' => '@link-best-sellers'
        ];
    }
}
```

**Comment by staudenmeir** [comment] 2018-10-10 16:31
The issue is `Dashboard::assert()`: The page automatically checks the URL and expects it to be `/` (but it's `/login`).

**Comment by thehiggster** [comment] 2018-10-26 11:11
Hi @staudenmeir ,

Thanks for your help mate.

The Dashboard::assert method is however, checking the correct path for the dashboard.

In the tests

assert("/") << passes
assert(new Dashboard()) << fails

Dashboard's url is checking ("/") and that is correct!

It's not meant to be and it's not on /login.

IS it to do with the order the asserts process, maybe?

Thanks, 
James

**Comment by staudenmeir** [comment] 2018-10-27 00:08
Dusk automatically calls `YourPage::assert()` when the page is loaded.

Try only `$browser->visit(new Dashboard());`:  The assertion fails because the browser gets redirected to the `/login` page.

**Comment by driesvints** [comment] 2018-11-01 12:46
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-11-01 12:46 UTC

**Comment by multimonos** [comment] 2020-12-04 22:13
Had this issue as well and found my solution was 

`$browser->visit(( new LandingPage() )->url())`
