### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by parvatmabohang** [laravel/dusk#560] opened 2018-10-03 04:44 UTC
Facebook\WebDriver\Exception\UnknownServerException: unknown error: Cannot read property 'click' of undefined
  (Session info: headless chrome=67.0.3396.79)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.15.0-34-generic x86_64)

**Comment by staudenmeir** [comment] 2018-10-03 13:14
What does your test look like?

**Comment by driesvints** [comment] 2018-11-01 12:46
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by scofield-ua** [comment] 2018-12-13 12:45
Received same error today. 

Tried to use `$browser->clickLink()` on a link with a `strong` tag inside it, like this:
```html
<a href="#">
   Some Text With a <strong>Text</strong>
</a>
```
Test code:
```php
$browser->clickLink('Some Text With a Text')
```

Get error in this case is it expected behavior?

@staudenmeir

**Comment by driesvints** [comment] 2018-12-13 12:47
@scofield-ua what happens when you try:

```php
$browser->clickLink('Some Text With a <strong>Text</strong>')
```

**Comment by scofield-ua** [comment] 2018-12-13 13:18
@driesvints hm.. same error: `Cannot read property 'click' of undefined`. Do I need to set up test repository?

**Comment by driesvints** [comment] 2018-12-13 13:36
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by scofield-ua** [comment] 2018-12-13 13:40
I will prepare repository with actual code and tests later today, thanks.

**Comment by scofield-ua** [comment] 2018-12-13 19:10
@driesvints can't reproduce it with a clean setup. Sorry.

**Comment by driesvints** [comment] 2018-12-13 20:05
No problem.

**Closed by driesvints** 2018-12-13 20:05 UTC
Labels: needs more info
