### ISSUE TITLE
check for text exist not consistent on modal (sometime dusk failed to assert true on the existed text)

### ISSUE THREAD

**Issue by batmahir** [laravel/dusk#277] opened 2017-05-19 11:32 UTC
i already tried using assertSee , waitForText method but the result it's not consistent , 
below is my code 
```
/**
     * Test create user with all empty data
     * @group create_user1
     * 
     * @return void
     */
    public function test_create_user_with_empty_data()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/')
                    ->type('email','nazrulmustaffa@gmail.com')
                    ->type('password','password')
                    ->click('.btn')
                    ->visit('sadmin')
                    ->clickLink('Users Management')
                    ->clickLink('Manage Users')
                    ->script("window.scrollTo(0, 500);");

            $browser->clickLink('Add New User')
                    ->waitFor('#add-new-user',5)
                    ->whenAvailable('#add-new-user', function ($modal) 
            {
                    $modal
                    ->press('Save')
                    ->pause('10000')
                    ->assertSee('Name is required')
                    ->assertSee('First Name is required')
                    ->assertSee('Last Name is required')
                    ->assertSee('Email is required')
                    ->assertSee('IC Number is required')
                    ->assertSee('Date of birth is required')
                    ->assertSee('Phone no is required')
                    ->assertSee('Address is required')
                    ->assertSee('City is required')
                    ->assertSee('State is required')
                    ->assertSee('Postcode is required')
                    ->assertSee('Country is required');
            });

                    
        });


    }
```
Here the screenshot for case 1 :
![failure-test_create_user_with_the_right_data-0](https://cloud.githubusercontent.com/assets/20837786/26244844/2277d3f8-3cc4-11e7-8d3f-da1c90d350d2.png)

Here the dusk response after complete on the terminal for case 1 : 

```
 php artisan dusk --group=create_user1
Warning: TTY mode is not supported on Windows platform.
PHPUnit 5.7.17 by Sebastian Bergmann and contributors.

[11732:10832:0519/184030.100:ERROR:navigation_entry_screenshot_manager.cc(135)] Invalid entry with unique id: 7
F                                                                   1 / 1 (100%)

Time: 18.73 seconds, Memory: 17.75MB

There was 1 failure:

1) Tests\Browser\UserManagement\CreateUserTest::test_create_user_with_the_right_data
Did not see expected text [Last Name is required] within element [body #add-new-user].
Failed asserting that false is true.

C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\Concerns\MakesAssertions.php:240
C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\Concerns\MakesAssertions.php:210
C:\Users\bathulahmahir\Documents\Code\Homestead\project\tests\Browser\UserManagement\CreateUserTest.php:38
C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\Browser.php:261
C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\Concerns\WaitsForElements.php:24
C:\Users\bathulahmahir\Documents\Code\Homestead\project\tests\Browser\UserManagement\CreateUserTest.php:49
C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\TestCase.php:91
C:\Users\bathulahmahir\Documents\Code\Homestead\project\tests\Browser\UserManagement\CreateUserTest.php:52

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
```
and next  for case no.2 

below here the screenshot for case 2 :

![failure-test_create_user_with_empty_data-0](https://cloud.githubusercontent.com/assets/20837786/26245252/cff84188-3cc5-11e7-8b8e-88919226d0fb.png)

Here the dusk response after complete on the terminal for case 2 :
```
php artisan dusk --group=create_user1
Warning: TTY mode is not supported on Windows platform.
PHPUnit 5.7.17 by Sebastian Bergmann and contributors.

[12088:9524:0519/190001.885:ERROR:navigation_entry_screenshot_manager.cc(135)] Invalid entry with unique id: 7
F                                                                   1 / 1 (100%)

Time: 28.96 seconds, Memory: 17.50MB

There was 1 failure:

1) Tests\Browser\UserManagement\CreateUserTest::test_create_user_with_empty_data
Did not see expected text [Date of birth is required] within element [body #add-new-user].
Failed asserting that false is true.

C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\Concerns\MakesAssertions.php:240
C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\Concerns\MakesAssertions.php:210
C:\Users\bathulahmahir\Documents\Code\Homestead\project\tests\Browser\UserManagement\CreateUserTest.php:41
C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\Browser.php:261
C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\Concerns\WaitsForElements.php:24
C:\Users\bathulahmahir\Documents\Code\Homestead\project\tests\Browser\UserManagement\CreateUserTest.php:48
C:\Users\bathulahmahir\Documents\Code\Homestead\project\vendor\laravel\dusk\src\TestCase.php:91
C:\Users\bathulahmahir\Documents\Code\Homestead\project\tests\Browser\UserManagement\CreateUserTest.php:51

FAILURES!
Tests: 1, Assertions: 6, Failures: 1.
```

Situation:
-  Case no. 1 and Case no. 2 are totally with same code.
-  Laravel Dusk giving the different result (this is my question to you guys)
-  Both of the below text are exist in the user interface inside my modal but dusk still throw an error: 
 ```
   i) 'Last Name is required'  - this for case 1 (this actually should not be an error but dusk throw an error)
   ii) 'Date of birth is required' -  this for case 2  (this actually should not be an error but dusk throw an error)
```
   
- Dusk result not consistent , sometime it detect it rightly (this is it's supposed to be) but sometime
   it cannot detect that text at my modal.
-  already tried with these methods assertSee and waitForText and actually i'm also already tried with waitFor method , but the result is just very similar to this.
-   both of the screenshot is actually taken by dusk (not manual screenshot)

Detail for my modal:
- have 18 fields
- because it have 18 fields so my modal can be scroll up or down
- normal one just html bootstrap jquery

Special Note : Dusk was able to verify and detect some of the other text on my modal but also fail to detect some of the other text.

**Comment by deleugpn** [comment] 2017-05-21 19:12
Are you sure `body #add-new-user` is the correct HTML address to the element and that the messages are inside this tag?

**Comment by bathulah** [comment] 2017-05-22 11:51
yes i'm sure , the issue is sometime dusk detect the one that shouldn't be error as error on the modal when the modal are a lot of input and that modal is scrollable(can be scroll down and up) .  The dusk detect very well when it's not in scrollable modal.

**Comment by driesvints** [comment] 2018-11-05 15:46
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-11-05 15:46 UTC
