### ISSUE TITLE
Changing the directory of [screenshots, console]

### ISSUE THREAD

**Issue by andrewmclagan** [laravel/dusk#466] opened 2018-02-18 12:06 UTC
I cant determine a method (seems like its been hardcoded) to change the directories for storing screenshots and console output.

Anyone aware of this limitation?

**Comment by staudenmeir** [comment] 2018-02-18 17:36
https://github.com/laravel/dusk/issues/393

**Comment by envision** [comment] 2018-02-18 19:05
https://github.com/laravel/dusk/pull/36

**Comment by driesvints** [comment] 2018-11-01 12:53
Duplicate of #393

**Closed by driesvints** 2018-11-01 12:53 UTC
