### ISSUE TITLE
Assert path doesn't work when Laravel run in a subfolder

### ISSUE THREAD

**Issue by eliurkis** [laravel/dusk#37] opened 2017-01-19 05:35 UTC
Using the following config:
`APP_URL=http://local7.dev/Quincalla/public`

Page Code:
```php
class HomePage extends Page
{
    public function url()
    {
        return '/';
    }

    public function assert(Browser $browser)
    {
        $browser->assertPathIs($this->url());
    }
}
```

Error returned:
```
There was 1 failure:

1) Tests\Browser\CartTest::testAddProductToCart
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/'
+'/Quincalla/public/'
```

A temporal solution to sort that was changing the `url` method on the `HomePage` to:

```php
public function url()
{
    return parse_url(config('app.url'))['path'] . '/';
}
```

Other solution could be modifying the method `assertPathIs` in `MakesAssertions` class as this:

```php
public function assertPathIs($path)
{
    PHPUnit::assertEquals(parse_url(config('app.url'))['path'] . $path, parse_url(
        $this->driver->getCurrentURL()
    )['path']);

    return $this;
}
```

Any thoughts?

**Comment by KKSzymanowski** [comment] 2017-01-19 08:49
I agree, the expected behaviour is to match the path. 

I know this is a local environment, but as Graham Campbell said
> We definitely don't recommend you run apps on sub-folders.

Assuming you don't run Valet, it's not very difficult to configure Apache or Nginx to run multiple virtual hosts accessed as `first-app.dev`, `second-app.dev` etc. and it can save you from similar unexpected behaviour in the future.

**Comment by deleugpn** [comment] 2017-03-13 19:12
I think assertPathIs is suppose to assert the path inside your application. What you want would be called `assertAddressIs()` or `AssertUrlIs()`. You can easily use a macro to achieve that while it is not supported. Although I'm not sure if there's any interest in supporting that at all. Did you try `assertRouteIs()`?

**Comment by Opsse** [comment] 2017-06-02 18:52
Same issue here. Obviously it's a bad practice to run apps on sub-folders, but I don't think that should raise error. Everything else in Laravel works perfectely with sub-folder.

The main issue come from `parse_url` which ignore `app.url`.

**Comment by driesvints** [comment] 2018-11-05 17:09
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-11-05 17:09 UTC

**Comment by MeekLogic** [comment] 2018-11-06 18:42
I am experiencing this running a self-managed development stack. I saved myself some time and instead of having to configure vhosts I just decided to use subdirectories. I see you guys have stated more than once that it is a bad idea to develop this way but not a single reason to back it up. Can someone please elaborate on why it is such a bad idea to develop this way? Otherwise, it's my opinion that Dusk just does not correctly handle parsing our app's URL and that this issue is valid and in need of fixing.
