### ISSUE TITLE
Failed Test Window Size 

### ISSUE THREAD

**Issue by kerimkuscu** [laravel/dusk#719] opened 2020-01-17 11:09 UTC
- Dusk Version: "~5.0",
- Laravel Version: "^6.4",
- PHP Version: "^7.4",
- Database Driver & Version:

### Description:
After running my browser tests repeatedly, the screen size of the running test automatically decreases after any test fails. In my screenshot, my DuskTestCase.php file is 'window-size = 1920, 1080', although my screen size is defined, it crushes it and reduces the screen size.

DuskTestCase.php file

```
/**
     * Create the RemoteWebDriver instance.
     *
     * @return RemoteWebDriver
     */
    protected function driver()
    {
        $options = (new ChromeOptions)->addArguments([
            '--disable-gpu',
//            '--headless',
            '--window-size=1920,1080',
        ]);
```

ScreenShot
![Screenshot from 2020-01-17 13-51-56 (1)](https://user-images.githubusercontent.com/43302726/72608032-db61f700-3932-11ea-989a-168274b14658.jpg)

**Comment by driesvints** [comment] 2020-01-17 13:23
Heya, this seems to be a duplicate of https://github.com/laravel/dusk/issues/715 which was fixed in https://github.com/laravel/dusk/pull/717 and will be in next week's release. Can you try `5.x-dev` to see if that fixes your problem?

**Comment by driesvints** [comment] 2020-01-27 10:59
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Closed by driesvints** 2020-01-27 10:59 UTC
Labels: needs more info

**Comment by kerimkuscu** [comment] 2020-01-27 11:05
I'm still having this problem. Nothing is resolved. I tried to explain with the screenshot. How can I give more information? @driesvints

**Comment by driesvints** [comment] 2020-01-27 11:13
@kerimkuscu I asked you to test 5.x-dev above but you didn't reply which is why I closed the issue. Can you please try the latest release?

**Comment by browner12** [comment] 2020-01-27 14:15
does it happen to be decreasing by a consistent amount each time? possibly 16px?

**Comment by kerimkuscu** [comment] 2020-01-27 16:18
@browner12 yes
