### ISSUE TITLE
After starting php artisan dusk is error - PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException

### ISSUE THREAD

**Issue by dborovsky** [laravel/dusk#387] opened 2017-10-13 08:22 UTC
I run php artisan dusk and get errors:

`
1 / 1 (100%)PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php:918
Stack trace:
#0 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/Ha in /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 918
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php:918
Stack trace:
#0 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/Ha in /home/vagrant/Code/jobboard/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 918
`

vagrant homestead 
PHPUnit 6.3.1
laravel 5.5

**Comment by mykytak** [comment] 2017-11-21 15:24
Same.
Docker version 17.09.0-ce, build afdb6d4
Laravel Framework 5.5.20
PHPUnit 6.4.4

**Comment by jgnovais** [comment] 2017-12-22 18:19
Hi, it same for me.

But i reinstall Chrome build 63.0.3239.108-1 and it works fine

**Comment by driesvints** [comment] 2018-11-05 13:14
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-11-05 13:14 UTC

**Comment by InstanceOfMichael** [comment] 2019-01-24 16:02
was never fixed, always happening randomly https://github.com/laravel/framework/issues/10808

**Comment by Tarasovych** [comment] 2019-03-28 08:15
Not fixed
Laravel 5.7.28, PHP 7.2.14, Dusk 5.0.2.

**Comment by staudenmeir** [comment] 2019-03-29 21:54
@InstanceOfMichael @Tarasovych Can you provide a minimal example that lets us reproduce the issue?

**Comment by InstanceOfMichael** [comment] 2019-04-16 13:57
We can't because it happens randomly. https://github.com/laravel/framework/issues/10808#issuecomment-457254302
