### ISSUE TITLE
Error after upgrading to Laravel 5.8

### ISSUE THREAD

**Issue by yannisc** [laravel/dusk#614] opened 2019-02-27 06:55 UTC
After updating to Laravel 5.8, when running php artisan dusk, I get:

Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Dotenv\Dotenv::__construct() must be an instance of Dotenv\Loader, string given, called in /vendor/laravel/dusk/src/Console/DuskCommand.php on line 208

**Comment by staudenmeir** [comment] 2019-02-27 07:13
Please add the result of `composer show`.

**Comment by yannisc** [comment] 2019-02-27 07:16
barryvdh/laravel-debugbar             v3.2.3     PHP Debugbar integration for Laravel
beyondcode/laravel-dump-server        1.2.2      Symfony Var-Dump Server for Laravel
cakephp/chronos                       1.2.4      A simple API extension for DateTime.
dnoegel/php-xdg-base-dir              0.1        implementation of xdg base directory specification for php
doctrine/inflector                    v1.3.0     Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.1.0      A small, lightweight utility to instantiate objects in PHP without invoking their const...
doctrine/lexer                        v1.0.1     Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression         v2.2.0     CRON for PHP: Calculate the next or previous run date and determine if a CRON expressio...
egulias/email-validator               2.1.7      A library for validating emails against several RFCs
erusev/parsedown                      1.7.1      Parser for Markdown.
facebook/webdriver                    1.6.0      A PHP client for Selenium WebDriver
fideloper/proxy                       4.1.0      Set trusted proxies for Laravel
filp/whoops                           2.3.1      php error handling for cool kids
firebase/php-jwt                      v5.0.0     A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to t...
fzaninotto/faker                      v1.8.0     Faker is a PHP library that generates fake data for you.
google/apiclient                      v2.2.2     Client library for Google APIs
google/apiclient-services             v0.87      Client library for Google APIs
google/auth                           v1.4.0     Google Auth Library for PHP
guzzlehttp/guzzle                     6.3.3      Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1     Guzzle promises library
guzzlehttp/psr7                       1.5.2      PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php                 v2.0.0     This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       v0.2
jakub-onderka/php-console-highlighter v0.4       Highlight PHP code in terminal
laravel/dusk                          v5.0.0     Laravel Dusk provides simple end-to-end testing and browser automation.
laravel/framework                     v5.8.0     The Laravel Framework.
laravel/nova                          dev-master A wonderful administration interface for Laravel.
laravel/socialite                     v4.1.0     Laravel wrapper around OAuth 1 & OAuth 2 libraries.
laravel/tinker                        v1.0.8     Powerful REPL for the Laravel framework.
league/flysystem                      1.0.50     Filesystem abstraction: Many filesystems, one API.
league/oauth1-client                  1.7.0      OAuth 1.0 Client Library
maximebf/debugbar                     v1.15.0    Debug bar in the browser for php application
mockery/mockery                       1.2.2      Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                       1.24.0     Sends your logs to files, sockets, inboxes, databases and various web services
moontoast/math                        1.1.2      A mathematics library, providing functionality for large numbers
myclabs/deep-copy                     1.8.1      Create deep copies (clones) of your objects
nesbot/carbon                         2.14.0     A simple API extension for DateTime.
nikic/php-parser                      v4.2.1     A PHP parser written in PHP
nunomaduro/collision                  v2.1.1     Cli error handling for console/command-line PHP applications.
opis/closure                          3.1.6      A library that can be used to serialize closures (anonymous functions) and arbitrary ob...
paragonie/random_compat               v9.99.99   PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                      1.0.3      Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       2.0.1      Library for handling version information and constraints
phpdocumentor/reflection-common       1.0.1      Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.0      With this component, a library can provide support for annotations via DocBlocks or oth...
phpdocumentor/type-resolver           0.4.0
phpoption/phpoption                   1.5.0      Option Type for PHP
phpseclib/phpseclib                   2.0.14     PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X...
phpspec/prophecy                      1.8.0      Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             7.0.3      Library that provides collection, processing, and rendering functionality for PHP code ...
phpunit/php-file-iterator             2.0.2      FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1      Simple template engine.
phpunit/php-timer                     2.1.1      Utility class for timing
phpunit/php-token-stream              3.0.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       8.0.4      The PHP Unit Testing framework.
psr/cache                             1.0.1      Common interface for caching libraries
psr/container                         1.0.0      Common Container Interface (PHP FIG PSR-11)
psr/http-message                      1.0.1      Common interface for HTTP messages
psr/log                               1.1.0      Common interface for logging libraries
psr/simple-cache                      1.0.1      Common interfaces for simple caching
psy/psysh                             v0.9.9     An interactive shell for modern PHP.
ralouphie/getallheaders               2.0.5      A polyfill for getallheaders.
ramsey/uuid                           3.8.0      Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and ...
sebastian/code-unit-reverse-lookup    1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator                  3.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                        3.0.2      Diff implementation
sebastian/environment                 4.1.0      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.0      Provides the functionality to export PHP variables for visualization
sebastian/global-state                3.0.0      Snapshotting of global state
sebastian/object-enumerator           3.0.3      Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector            1.1.1      Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context           3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations         2.0.1      Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1      Library that helps with managing the version number of Git-hosted PHP projects
spatie/once                           1.1.0      A magic memoization function
swiftmailer/swiftmailer               v6.1.3     Swiftmailer, free feature-rich PHP mailer
symfony/console                       v4.2.3     Symfony Console Component
symfony/contracts                     v1.0.2     A set of abstractions extracted out of the Symfony components
symfony/css-selector                  v4.2.3     Symfony CssSelector Component
symfony/debug                         v4.2.3     Symfony Debug Component
symfony/event-dispatcher              v4.2.3     Symfony EventDispatcher Component
symfony/finder                        v4.2.3     Symfony Finder Component
symfony/http-foundation               v4.2.3     Symfony HttpFoundation Component
symfony/http-kernel                   v4.2.3     Symfony HttpKernel Component
symfony/polyfill-ctype                v1.10.0    Symfony polyfill for ctype functions
symfony/polyfill-mbstring             v1.10.0    Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                v1.10.0    Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                       v4.2.3     Symfony Process Component
symfony/routing                       v4.2.3     Symfony Routing Component
symfony/translation                   v4.2.3     Symfony Translation Component
symfony/var-dumper                    v4.2.3     Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                     1.1.0      A small library for converting tokenized PHP source code into XML and potentially other...
tijsverkoyen/css-to-inline-styles     2.2.1      CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pag...
vlucas/phpdotenv                      v3.3.2     Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagic...
webmozart/assert                      1.4.0      Assertions to validate method input/output with nice error messages.

**Comment by staudenmeir** [comment] 2019-02-27 07:30
The issue is that Dusk 5.0 wants to support both Laravel 5.7 and 5.8, but they require different versions of the `vlucas/phpdotenv`  package (`^2.2` vs. `^3.3`).

**Comment by yannisc** [comment] 2019-02-27 07:35
phpdotenv 3.3 came with Laravel 5.8. Should I downgrade to 2.2?

**Comment by staudenmeir** [comment] 2019-02-27 07:41
Composer won't let you do that and it would break Laravel.

I don't think there's anything you can do right now. This has to be fixed by Dusk.

**Comment by yannisc** [comment] 2019-02-27 07:43
I think the same. Thanks for your help!

**Closed** 2019-02-27 11:21 UTC

**Comment by driesvints** [comment] 2019-02-27 11:22
Released v5.0.1 which should fix this.

**Comment by yannisc** [comment] 2019-02-27 11:51
Thanks, @driesvints! That fixed the problem!
