### ISSUE TITLE
unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by Kayrah87** [laravel/dusk#1051] opened 2023-08-01 08:10 UTC
### Dusk Version

7.9.2

### Laravel Version

9.52.10

### PHP Version

8.2.8

### PHPUnit Version

9.6.9

### Description

Having updated recently to get the 115 version of Chrome working, I now cannot run any tests. It states that it cannot find the Chrome Binary.

please see output below:

```
PHPUnit 9.6.9 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 00:00.593, Memory: 26.00 MB

There was 1 error:

1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnknownErrorException: unknown error: cannot find Chrome binary

/Users/kay/Work/Repos/TCC/tcc-v2/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:146
/Users/kay/Work/Repos/TCC/tcc-v2/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:359
/Users/kay/Work/Repos/TCC/tcc-v2/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:129
/Users/kay/Work/Repos/TCC/tcc-v2/tests/DuskTestCase.php:41
/Users/kay/Work/Repos/TCC/tcc-v2/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:220
/Users/kay/Work/Repos/TCC/tcc-v2/vendor/laravel/framework/src/Illuminate/Support/helpers.php:247
/Users/kay/Work/Repos/TCC/tcc-v2/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:219
/Users/kay/Work/Repos/TCC/tcc-v2/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:99
/Users/kay/Work/Repos/TCC/tcc-v2/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:67
/Users/kay/Work/Repos/TCC/tcc-v2/tests/Browser/ExampleTest.php:16
```

This is on a new installation of Dusk

### Steps To Reproduce

```
php artisan dusk:install
php artisan dusk
```

**Comment by crynobone** [comment] 2023-08-01 08:15
Duplicate of #1046

**Closed by crynobone** 2023-08-01 08:15 UTC
