### ISSUE TITLE
Laravel Dusk on Travis CI - Unable to locate element

### ISSUE THREAD

**Issue by StanBarrows** [laravel/dusk#474] opened 2018-02-28 18:08 UTC
Hello together. I'm currently facing a problem with Laravel Dusk on Travis CI.

**Error**

```
2) Tests\Browser\Tests\Auth\SignInTest::a_user_can_sign_in
Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"body textarea[name='#email']"}
  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.4.0-101-generic x86_64)
```

**Local Environment**
I've to mention that all tests (phpunit & dusk) are working on my local machine. 

**Travis Environment**
Except of the tests where an element is needed als tests are working as well.

Set [Travis ENV](http://prntscr.com/il11b0) as well.
[Link to Travis-CI Test-Message](http://prntscr.com/il0rh4)
[Full Error Message Log from Travis-CI](http://prntscr.com/il0szd)

I also tried different ways of selecting the element like:
-  -> type('email', $user->email)
-  ->type('@email', $user->email and then define it in the elements method.

#454 Checked already this out. Not working as well for me. Unfortunately am at the end with my knowledge.. any suggestions?

Cheers, Stan

**Sign-In-Page**

```
public function assert(Browser $browser)
    {
        $browser->assertPathIs($this->url());
    }

    public function signIn(Browser $browser, $email = null, $password = null)
    {
        $browser
            ->resize(1920, 1080)
            ->type('@login-email', $email)
            ->type('@login-password', $password)
            ->click('@login-button');
    }


    /**
     * Get the element shortcuts for the page.
     *
     * @return array
     */
    public function elements()
    {
        return [
        ];
    }
```

**Sign-In-Test**

```
public function a_user_can_sign_in()
        {
            $path = route('login');

            $user = factory(User::class)->create([

                'name' => 'Max Mustermann',
                'email' => 'max.mustermann@testing.ch',
                'password' => bcrypt('password')

            ]);

            $this->browse(function ($browser) use ($path, $user) {
                $browser
                    ->visit(new SignInPage)
                    ->signIn($user->email, 'password')
                    ->assertPathIs('/backend/users/dashboard')
                    ->assertSeeIn('.navbar', $user->name);
            });
        }
```

**Login Template Blade**

<div class="form-group row">

                            <div class="col-lg-8 offset-2">
                                <input   dusk="login-email"
                                        title="E-mail"
                                        placeholder="E-mail"
                                        id="email"
                                        type="email"
                                        class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                        name="email"
                                        value="{{ old('email') }}"
                                        required
                                        autofocus
                                >

                                @if ($errors->has('email'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>

**.env.dusk.testing**

```
    APP_NAME=Testing
    APP_ENV=testing
    APP_KEY=
    APP_DEBUG=true
    APP_LOG_LEVEL=debug
    APP_URL=http://do.testing.test

    DB_CONNECTION=pgsql
    DB_DATABASE=testing
    DB_USERNAME=postgres
    DB_PASSWORD=

    BROADCAST_DRIVER=log
    CACHE_DRIVER=array
    SESSION_DRIVER=database
    QUEUE_DRIVER=sync

    MAIL_FROM_NAME= Testing
    MAIL_FROM_ADDRESS=do@testing.test

    MAIL_DRIVER=log
```

**travis.yml**

```
sudo: true

dist: trusty

language: php

env:
  global:
    - CC_TEST_REPORTER_ID=

addons:
  chrome: stable

  code_climate:
    repo_token:
      secure:

php:
  - 7.2

services:
  - redis-server
  - postgres

before_script:
   - psql -c 'create database testing;' -U postgres
   - cp .env.travis .env
   - cp phpunit.travis.xml phpunit.xml

    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - php artisan serve &

install:
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

   - cp .env.travis .env
   - cp phpunit.travis.xml phpunit.xml

   - php artisan key:generate

script:
  - phpunit
  - php artisan dusk

after_script:
  - vendor/bin/test-reporter

after_success:
  - chmod +x ./tests.sh; ./tests.sh
```

**Comment by staudenmeir** [comment] 2018-02-28 18:51
If you dump the page source before `->type()`, do you get the expected HTML?

**Comment by StanBarrows** [comment] 2018-02-28 20:33
hey @staudenmeir thanks for your message, the dump seems to be correct. I can see all expected elements.  [Dump Travis CI](http://prntscr.com/il2vgq)

**Comment by staudenmeir** [comment] 2018-02-28 22:35
Can you find other elements? Something like this: `$browser->element('body');`

Is the HTML valid?

**Comment by dmarcos89** [comment] 2018-03-01 10:27
Hi @staudenmeir @StanBarrows, im facing a similar issue. How do you actually dump the page content from a dusk test?

**Comment by dmarcos89** [comment] 2018-03-01 10:32
found it:  ->dump()

**Comment by dmarcos89** [comment] 2018-03-01 10:33
found it:  ->dump()

**Comment by braian125** [comment] 2018-03-20 21:46
This problem is solved easily, specifying the url in the **.env** file, in my case, as I am using a virtual host, change APP_URL = http: //app.local instead of APP_URL = http: // localhost (by default in laravel). This way you can access the view and laravel dusk can find the input and what you define to complete your test.

**Comment by staudenmeir** [comment] 2018-10-07 19:42
@StanBarrows Are you still having this issue?

**Comment by driesvints** [comment] 2018-11-01 13:39
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-11-01 13:39 UTC

**Comment by zahirzohair** [comment] 2019-04-05 08:02
hi everyone, i go the same error and googled a lot but could not solve it yet. any new solution  for this?
the error i got:

1) Tests\LoginTest::testExample
Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"cs
s selector","selector":"body textarea[name='email']"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.
17134 x86_64)

------------------------------------------------------------------------------------------------

my test class:

namespace Tests;
use Tests\TestCase;
use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class LoginTest extends DuskTestCase
{
    use DatabaseMigrations;
    /**
     * A Dusk test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/#!/auth')
                    ->assertSee('Login')
                    ->type('email', 'siteadmin@webspecdesign.com')
                    ->type('password', '23wesdxc')
                    ->press('Log in')
                    ->assertPathIs('/#!');
        });
    }
}

**Comment by staudenmeir** [comment] 2019-04-05 08:14
Do you see the `email` field when you append `->dump();` after `->assertSee('Login')`?

**Comment by zahirzohair** [comment] 2019-04-08 02:28
> Do you see the `email` field when you append `->dump();` after `->assertSee('Login')`?

No cannot see that, sorry for late reply

**Comment by staudenmeir** [comment] 2019-04-08 02:45
Do you see the rest of the page? Or is the dump basically empty?

Are you using JavaScript to insert the `email` field?

**Comment by zahirzohair** [comment] 2019-04-08 02:57
> Do you see the rest of the page? Or is the dump basically empty?
> 
> Are you using JavaScript to insert the `email` field?
ooh sorry, i can see the email field:
this is part of what i get after using  ->dump();
                \t<div class="form-group" _v-0e2fc5c5="">\n
                \t\t<label for="email" _v-0e2fc5c5="">Email</label>\n
                \t\t<input type="email" id="email" class="form-control" placeholder="Email" autofocus="" _v-0e2fc5c5=""
 />\n
                \t</div>\n
\n
                \t<div class="form-group" _v-0e2fc5c5="">\n
                \t\t<label for="password" _v-0e2fc5c5="">Password</label>\n
                \t\t<input type="password" id="password" class="form-control" placeholder="Password" _v-0e2fc5c5="" />\
n
                \t</div>\n
\n
                \t <div class="pull-left" _v-0e2fc5c5="">\n
                    \t<a _v-0e2fc5c5="" href="#!/auth/forgot">Forgot Password?</a>\n
                    </div>\n
\n
                    <div class="form-group" _v-0e2fc5c5="">\n
                        <button type="submit" class="btn btn-default pull-right" _v-0e2fc5c5="">\n
                        \tLog in <i class="fa fa-arrow-circle-right" _v-0e2fc5c5=""></i>\n
                    \t</button>\n
                    </div>\n
                </form>\n

**Comment by staudenmeir** [comment] 2019-04-08 03:00
Did you delete your original post?

**Comment by zahirzohair** [comment] 2019-04-08 03:08
> Did you delete your original post?
yes, this is the test function and the error : 

 public function testExample()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/#!/auth')
                    ->assertSee('Email');
                    ->type('email', 'abc@example.com')
                    ->type('password', 'abc123')
                    ->press('Log in')
                    ->assertPathIs('/#!');
        });
    }
-------------------------------------
this is the error i got:  
 Tests\LoginTest::testExample
Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"css selector
","selector":"body textarea[name='email']"}

**Comment by staudenmeir** [comment] 2019-04-08 03:11
Please create a minimal application to reproduce the issue and upload it to GitHub.

**Comment by zahirzohair** [comment] 2019-04-08 03:53
> Please create a minimal application to reproduce the issue and upload it to GitHub.

I found it!
silly mistake, i have to select the fields based on their Ids not their names. that is why it could not find the email field.
basically, it should be something like this:

$browser->visit('/#!/auth')
->assertSee('Login');
->type('#email', 'abc@example.com')
->type('#password', 'abc123')
->press('Log in')
->assertPathIs('/#!');
});

Btw, thank you very much for your effort and time.

**Comment by p4rz1val** [comment] 2019-09-22 09:38
Another possible solution:

Between load pages or at the star of your Dusk test add a big pause, Travis VM runs considerably slower than your local pc.

```
// Wait for Travis CI to load the page
if (App::environment('testing')) {
    $browser->pause(10000);
}                              
            
```
